### ISSUE TITLE
在linux运行效果没有windows上好，有杂音，不知道为什么

### ISSUE THREAD

**Issue by YFJiang** [EasyDarwin/EasyAACEncoder#1]

**Comment by leemeng0x61** [comment]
cannot find -lg7112aac

**Comment by VintageCar** [comment]
@YFJiang 最新的版本已修复这个问题

**Comment by babosa** [comment]
修改点：https://github.com/EasyDarwin/EasyAACEncoder/commit/fc357b7ebf4f2705dc2cb0c18d9476aceeee5ccb
